services:

  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5001:5432"