services:

  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5001:5432"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - 80:80
    depends_on:
      - postgres